[Spring Core] 이준영 과제 제출합니다.
BCSDLab-Edu/2024-BackEnd pull request #1
Opened 2024-05-31 12:57 UTC by ff1451

2024-06-04 14:58 UTC, kwoo28 requested changes
예외처리에 대해 고민을 많이 하신게 느껴지네요. 정말 수고 많으셨습니다! dto하고 model 몇몇개의 파일이 빠진것같은데 한번 확인해주세요!

2024-06-04 14:58 UTC, kwoo28 commented on src/main/java/com/example/demo/controller/dto/request/ArticleCreateRequest.java
> +        String description
이렇게되면 ""나 " "는 허용하게 돼서 제대로 검증하지 못할것같네요. NotBlank를 쓰는건 어떨까요?

2024-06-04 14:58 UTC, kwoo28 commented on src/main/java/com/example/demo/service/ArticleService.java
>      }
아무런 데이터를 찾을 수 없으면 빈 리스트가 반환될것같은데, 혹시 존재하지 않는 id값을 넣어서 확인해보셨나요?

2024-06-04 14:58 UTC, kwoo28 commented on src/main/java/com/example/demo/service/ArticleService.java
>      public ArticleResponse update(Long id, ArticleUpdateRequest request) {
ArticleUpdateRequest 클래스가 안보이네요..

2024-06-04 14:58 UTC, kwoo28 commented on src/main/java/com/example/demo/exception/ErrorCode.java
> +    INVALID_BOARD(400, "BAD REQUEST", "존재하지 않는 게시판을 참조하고 있습니다."),
이건 위에 쓰인 404오류랑 무슨 차이인가요??

2024-06-04 14:58 UTC, kwoo28 commented on src/main/java/com/example/demo/exception/ErrorCode.java
> +    EXIST_ARTICLE(400, "BAD REQUEST", "사용자 혹은 게시판과 연관된 게시물이 존재합니다."),
이미 존재한다는 상태코드가 400인건 이상한것같습니다. 또한 불분명한 '혹은'과 같은 메시지는 지양해야하며, ErrorCode이름과 목적이 일치해야합니다.

2024-06-04 14:58 UTC, kwoo28 commented on src/main/java/com/example/demo/exception/NullValueException.java
> +public class NullValueException extends RuntimeException {
음.. 이 클래스만 보고 어떤 기능을 하는지 잘 모르겠네요... 어떤 예외상황에서 쓰이는 용도인가요?

2024-06-04 14:58 UTC, kwoo28 commented on src/main/java/com/example/demo/service/BoardService.java
> +        if (articleRepository.existsByBoardId(id)) {
articleRepository.findByBoardId(id)로부터 null값인지 아닌지 판별하면 될것같습니다. 현재 로직은 Repository에서 필요없는 책임을 갖게되는것같아요.

2024-06-05 02:07 UTC, ff1451 commented on src/main/java/com/example/demo/service/ArticleService.java
>      public ArticleResponse update(Long id, ArticleUpdateRequest request) {
브랜치 나눈 후 변경사항이 없었어서 push 해야한다는 것을 깜빡했습니다. 누락 파일들 다시 추가했습니다. 죄송합니다.

2024-06-05 02:22 UTC, ff1451 commented on src/main/java/com/example/demo/exception/ErrorCode.java
> +    INVALID_BOARD(400, "BAD REQUEST", "존재하지 않는 게시판을 참조하고 있습니다."),
404 오류에서는 사용자, 게시판, 게시물을 조회할 때 해당 데이터가 없을 경우 발생하는 것을 의도했고
400 오류에서는 게시물을 생성할 때 존재하지 않는 데이터를 참조할 경우 발생하는 것을 의도했습니다.

2024-06-05 02:24 UTC, ff1451 commented on src/main/java/com/example/demo/exception/NullValueException.java
> +public class NullValueException extends RuntimeException {
처음 코드 작성할 때 Validation을 몰랐어서 별도로 커스텀 예외 클래스를 만들었는데 이후 제거를 안한것 같습니다. 수정하도록 하겠습니다.

2024-06-05 02:36 UTC, ff1451 commented on src/main/java/com/example/demo/controller/dto/request/ArticleCreateRequest.java
> +        String description
말씀해주신 대로 @NotBlack가 더 적절한것 같습니다.  수정하도록 하겠습니다. 감사합니다

2024-06-05 02:38 UTC, ff1451 commented on src/main/java/com/example/demo/exception/ErrorCode.java
> +    EXIST_ARTICLE(400, "BAD REQUEST", "사용자 혹은 게시판과 연관된 게시물이 존재합니다."),
과제 요구사항에서 400을 반환한다로 되어있었는데 그러면 Error code의 이름과 메시지를 수정하는 것이 좋을까요?
불분명한 문제와 목적 일치 부분은 수정하도록 하겠습니다.

2024-06-05 02:39 UTC, ff1451 commented on src/main/java/com/example/demo/service/BoardService.java
> +        if (articleRepository.existsByBoardId(id)) {
articleRepository.findByBoardId(id)이 부분이 null값 판별하면 된다는 생각을 하지 못했네요 관련 내용도 수정하도록 하겠습니다.

2024-06-05 02:47 UTC, ff1451 commented on src/main/java/com/example/demo/service/ArticleService.java
>      }
확인해보니 말씀대로 빈 리스트가 반환되고 있습니다. 확인해보는 과정에서 실수하여 해당 부분은 확인을 안해봤던 것같습니다. 다음부터는 꼼꼼하게 확인하도록 하겠습니다.

2024-07-03 09:14 UTC, kwoo28 reviewed
과제 하느라 수고 많으셨습니다!

2024-07-03 09:14 UTC, kwoo28 commented on src/main/java/com/example/demo/service/BoardService.java
> +    private final ArticleRepository articleRepository;
final같은 경우엔 롬북기능중에 @requiredargsconstructor를 쓰게되면 생성자를 입력 안해도 자동으로 생성자 빈 주입이 됩니다!

2024-07-03 09:14 UTC, kwoo28 commented on src/main/java/com/example/demo/repository/BoardRepository.java
>  }
현재 PR에 제거된 코드라고 뜨는데 혹시 커밋이 잘못된걸까요?

2024-07-03 09:14 UTC, kwoo28 commented on src/main/java/com/example/demo/domain/Board.java
> +    private List<Article> articles = new ArrayList<>();
해당 부분은 왜 cascade = CascadeType.ALL로 했나요??

2024-07-03 09:14 UTC, kwoo28 commented on src/main/java/com/example/demo/domain/Member.java
> +    private List<Article> articles = new ArrayList<>();
이 부분은 cascade를 적용안한 이유가 있을까요?

2024-07-04 08:24 UTC, ff1451 commented on src/main/java/com/example/demo/domain/Member.java
> +    private List<Article> articles = new ArrayList<>();
글을 쓴 작성자가 탈퇴하더라도 게시글은 지워지지 않는 사이트들을 생각해서 작성자가 삭제되더라도 게시글은 남아있도록 적용하지 않았습니다.

2024-07-04 08:41 UTC, ff1451 commented on src/main/java/com/example/demo/domain/Board.java
> +    private List<Article> articles = new ArrayList<>();
게시판과 게시글의 생명주기를 동일하게 해서 게시판이 제거되거나 수정, 생성될 때 게시글도 같이 동일한 동작이 수행되도록 하기 위해 ALL을 사용했습니다.

2024-07-10 06:31 UTC, kwoo28 reviewed
생소한 보안 기능을 조사하고 구현하시느라 어려웠을텐데 수고 많으셨습니다. email과 password 로그인을 통해서 쿠키를 구현할 수 있게해보고, 다른 API에서 쿠키를 활용할 수 있게 리팩토링 하는 방식으로도해보시면 좋을것같습니다!!

2024-07-10 06:31 UTC, kwoo28 commented on src/main/java/com/example/demo/controller/dto/request/LoginRequest.java
> +}
현재 이름,이메일,비밀번호으로 회원가입하게되는데 유저는 어덯게 PK인 id값을 알 수 있을까요?

2024-07-10 06:31 UTC, kwoo28 commented on src/main/java/com/example/demo/controller/MemberController.java
> +    }
cookie의 userId를 반환하게된다면, 추후 다른 API 쓸때 쿠키를 어덯게 이용할지에 대해서도 구현해보시면 좋을것같습니다

2024-07-10 06:31 UTC, kwoo28 commented on src/main/java/com/example/demo/controller/dto/request/LoginRequest.java
> +}
email과 password의 로그인을 통해서 쿠키를 이용할 수 있게 리팩토링 해 보시면 좋을것같습니다!

2024-07-10 06:31 UTC, kwoo28 commented on src/main/java/com/example/demo/controller/MemberController.java
> +@RequiredArgsConstructor
그때 말씀드렸던 롬복기능 적용하셨네요! 피드백 반영 감사합니다

2025-06-07 12:35 UTC, closed without merging